/// The generated crate.
///
/// A WASI command module: it reads one request from stdin, answers it, and
/// writes one response envelope to stdout. `@@` tokens stand in for a
/// `format!` template, because the module is mostly braces.
pub(super) const MAIN: &str = r#"//! Generated by rivet. Do not edit; run `rivet build --target wasm` again.
//!
//! An edge handler: one request in on stdin, one response out on stdout. The
//! route logic in `mod service` is the same code the native target compiles.

use std::io::{Read, Write};
@@STRUCTS@@

@@HELPERS@@

@@SERVICE@@

/// Run one service future to completion.
///
/// Every generated route is an `async fn` that never awaits: the parser's
/// subset holds literals, request parameters, and one DTO construction, so a
/// future is ready on its first poll. One poll with a no-op waker is the
/// whole executor, and the module carries no async runtime.
mod rivet_executor {
    use std::future::Future;
    use std::pin::pin;
    use std::task::{Context, Poll, Waker};

    /// Run one future to completion.
    ///
    /// A future that returned `Pending` would spin here, which is why the
    /// generated routes hold no I/O: this module has no reactor to make
    /// progress on it. See `docs/pillars/08-wasm-mobile-sdk-support.md`.
    pub(super) fn block_on<F: Future>(future: F) -> F::Output {
        let mut future = pin!(future);
        let waker = Waker::noop();
        let mut context = Context::from_waker(waker);
        loop {
            if let Poll::Ready(output) = future.as_mut().poll(&mut context) {
                return output;
            }
        }
    }
}

/// The paths this module serves, so an unknown path answers `404` and a known
/// path with the wrong method answers `405`.
const RIVET_DECLARED_PATHS: &[&str] = &[@@PATHS@@];

/// Percent-decode a URL-encoded path segment.
///
/// The request path was split into segments before decoding, so an encoded
/// `%2F` decodes to a slash inside one segment rather than a separator. A
/// `+` is a literal plus in a path segment, not a space.
///
/// Unused when no route declares a path parameter, which is a blueprint shape
/// and not a defect, so the function carries an allow.
#[allow(dead_code)]
fn rivet_percent_decode(segment: &str) -> String {
    let bytes = segment.as_bytes();
    let mut decoded: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' && index + 2 < bytes.len() {
            let high = rivet_hex_value(bytes[index + 1]);
            let low = rivet_hex_value(bytes[index + 2]);
            if let (Some(high), Some(low)) = (high, low) {
                decoded.push((high << 4) | low);
                index += 3;
                continue;
            }
        }
        decoded.push(bytes[index]);
        index += 1;
    }
    String::from_utf8_lossy(&decoded).into_owned()
}

/// The numeric value of one hexadecimal digit, or `None`.
///
/// Only [`rivet_percent_decode`] calls it, so it carries the same allow.
#[allow(dead_code)]
fn rivet_hex_value(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

/// Whether a requested path matches a declared path pattern.
///
/// `segments` is the request path split on `/`, before decoding. A `{name}`
/// segment matches any non-empty requested segment; every other segment must
/// equal the requested segment literally.
fn rivet_path_matches(segments: &[&str], pattern: &str) -> bool {
    let mut expected = pattern.split('/');
    for segment in segments {
        match expected.next() {
            Some(literal) => {
                let placeholder = literal.starts_with('{') && literal.ends_with('}');
                if placeholder {
                    if segment.is_empty() {
                        return false;
                    }
                } else if *segment != literal {
                    return false;
                }
            }
            None => return false,
        }
    }
    expected.next().is_none()
}

/// The methods one path answers, for a `405` answer.
fn rivet_allowed_methods(path: &str) -> &'static str {
    let segments: Vec<&str> = path.split('/').collect();
    for &declared in RIVET_DECLARED_PATHS {
        if rivet_path_matches(&segments, declared) {
            return match declared {
@@ALLOWED@@
                _ => "",
            };
        }
    }
    ""
}

/// Answer one request: `Ok(body)` for a `200`, or the status and message for
/// a `400`, `404`, or `405`.
///
/// The function is `async` because the service layer is: the executor polls
/// it inside `rivet_answer`.
///
/// `body` is unused when no route takes a JSON body, which is a blueprint
/// shape and not a defect, so the parameter carries an allow rather than a
/// renamed binding the dispatch arms would have to match.
#[allow(unused_variables)]
async fn rivet_dispatch(
    method: &str,
    path: &str,
    body: Option<&str>,
) -> Result<serde_json::Value, (u16, String)> {
    let segments: Vec<&str> = path.split('/').collect();
    let mut known = false;
@@DISPATCH@@
    if !known {
        return Err((404, format!("no route serves {path}")));
    }
    Err((
        405,
        format!(
            "{method} is not served by {path}; it allows {}",
            rivet_allowed_methods(path)
        ),
    ))
}

/// Answer an error body: `{"error": "..."}`.
fn rivet_json_error(message: &str) -> serde_json::Value {
    let mut object = serde_json::Map::new();
    object.insert(
        "error".to_string(),
        serde_json::Value::String(message.to_string()),
    );
    serde_json::Value::Object(object)
}

/// Read the request, answer it, and write the response envelope.
///
/// The request is `{"method": "GET", "path": "/ping", "body": "{...}"}`, and
/// the response is `{"status": 200, "body": {...}}`. An unreadable request
/// answers `400` rather than exiting: an edge host reads the envelope to
/// decide the HTTP status, so the module always writes one.
fn main() {
    let mut raw = String::new();
    let read = std::io::stdin().read_to_string(&mut raw);
    let (status, body) = match read {
        Ok(_) => rivet_answer(&raw),
        Err(err) => (400, rivet_json_error(&format!("cannot read the request: {err}"))),
    };

    let mut envelope = serde_json::Map::new();
    envelope.insert("status".to_string(), serde_json::Value::from(status));
    envelope.insert("body".to_string(), body);
    let envelope = serde_json::Value::Object(envelope).to_string();

    let mut stdout = std::io::stdout();
    if stdout.write_all(envelope.as_bytes()).is_err() {
        std::process::exit(1);
    }
}

/// The request body as text.
///
/// A host may send the body either as a JSON string (the raw body) or as a
/// JSON value (the parsed body). Both mean the same request, so a value is
/// re-serialized rather than rejected: answering 400 because a body arrived
/// parsed would blame the client for a shape it cannot know about.
fn rivet_body_text(request: &serde_json::Value) -> Option<String> {
    match request.get("body") {
        Some(serde_json::Value::String(text)) => Some(text.clone()),
        Some(value) if !value.is_null() => Some(value.to_string()),
        _ => None,
    }
}

/// Parse one request and answer its envelope body.
fn rivet_answer(raw: &str) -> (u16, serde_json::Value) {
    let request: serde_json::Value = match serde_json::from_str(raw) {
        Ok(request) => request,
        Err(err) => return (400, rivet_json_error(&format!("cannot read the request: {err}"))),
    };
    let method = request.get("method").and_then(serde_json::Value::as_str);
    let path = request.get("path").and_then(serde_json::Value::as_str);
    let (Some(method), Some(path)) = (method, path) else {
        return (400, rivet_json_error("the request names no method or path"));
    };
    let body = rivet_body_text(&request);
    match rivet_executor::block_on(rivet_dispatch(method, path, body.as_deref())) {
        Ok(value) => (200, value),
        Err((status, message)) => (status, rivet_json_error(&message)),
    }
}
"#;
